[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bcrypt = "0.15.1"
dotenvy = "0.15.7"
rocket = { version = "0.5.1", features = ["json"] }
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio"] }
